config/routes.rb
Rails.application.routes.draw do
  resources :scenes do
    get 'renderer', on: :new
    resources :jobs, shallow: true
  end
  resources :users
  resources :nodes, only: [:show, :index], constraints: { id: /[^\/]+/ }, format: false
  resources :renderers, only: [:show, :index, :update], constraints: { id: /[^\/]+/ }, format: false
  resources :options, only: [:show, :index, :update]
  root to: 'visitors#index'
  match '/auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/scene.rb
require 'json'

class Scene < ActiveRecord::Base
  include Adaptorable

  belongs_to :user
  has_many :jobs

  validates :title, presence: true
  validates :user, presence: true
  validates :scene_path, presence: true

  def method_missing(name, *args)
    match = /^option_(\w+)$/.match name
    return get_option(match[1]) if match

    match = /^option_(\w+)=$/.match name
    return options[match[1]] = args[0] if match

    super
  end

  def renderer
    Renderer.find(renderer_id)
  end

  def submit
    job_list = post 'submit', path: scene_path, renderer_id: renderer_id, options: JSON.dump(options)
    job_list.each do |job|
      jobs.build(id_remote: job['id'], result_path: job['path'], name: job['name'])
    end
  end

  # How many of the jobs are done
  # @return [Fixnum] 0-1 representing percentage of jobs done
  def amount_done
    # TODO Do in SQL
    return 1 if jobs.empty?
    num_completed = jobs.find_all { |job| job.completed? }.count
    puts num_completed
    puts jobs.count
    num_completed.to_f / jobs.count
  end

  # For listing previews
  def result
    return nil if jobs.empty?
    jobs[0].result
  end

  protected

  def get_option(name)
    return options[name] if options.has_key? name
    renderer.generator.option_value name
  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]

  # TODO reduce renderer lookups

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
    @scene.jobs.each { |job| job.update_state } # TODO do in a regular rake task
  end

  # GET /scenes/renderer
  # Select renderer for a new scene
  def renderer
    @renderers = Renderer.all
  end

  # GET /scenes/new
  def new
    if params[:renderer] && Renderer.valid(params[:renderer])
      @scene = Scene.new(renderer_id: params[:renderer])
    else
      redirect_to renderer_new_scene_url
    end
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)
    @scene.user = current_user
    begin
      scene_path = process_scene_file(scene_file_param)
      @scene.scene_path = scene_path
    rescue ActionController::ParameterMissing
      @file_missing = true
    end
    @scene.submit

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render :show, status: :created, location: @scene }
      else
        format.html { render :new }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { render :show, status: :ok, location: @scene }
      else
        format.html { render :edit }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url, notice: 'Scene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(*allowed_params(renderer_id_param))
    end

    def renderer_id_param
      params.require(:scene).require(:renderer_id)
    end

    def allowed_params(renderer_id)
      param_names = [ :title, :user_id, :renderer_id ]
      renderer = Renderer.find(renderer_id)
      renderer.generator_options.each do |option|
        param_names << "option_#{option.id}"
      end
      param_names
    end

    def scene_file_param
      params.require(:scene).require(:scene_file)
    end

    # Save the given file io to a secrets specified location, timestamp it and return the file path
    # @return [String] the full path to the saved scene file
    def process_scene_file(file_io)
      target_filename = scene_target_filename file_io.original_filename
      puts 'Opening file'
      File.open(target_filename, 'wb') do |file|
        file.write(file_io.read)
      end
      target_filename
    end

    def scene_target_filename(filename)
      stripped_filename = I18n.transliterate(filename).gsub(/[^0-9A-Za-z_.]/, '').downcase
      "#{Rails.application.secrets.fitrender_scenes_location}/#{Time.now.to_i}_#{stripped_filename}"
    end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.haml
- renderer = @scene.renderer

= simple_form_for(@scene, :html => {:multipart => true }) do |f|
  = f.error_notification

  .form-inputs
    = f.hidden_field :renderer_id

    %ul.small-block-grid-1.medium-block-grid-2
      %li.grid__item= f.input :title
      %li.grid__item
        %div
          %label{for: 'scene_file'}= "* #{'scene_file'.humanize}"
          = f.file_field :scene_file
          - if @file_missing
            %small.error= t 'scene.new.file_missing'

    %h2= t 'scene.new.options'

    %ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3
      %li.grid__item
        %div
          %label Renderer
          %p
            %strong=renderer.name
      - renderer.generator_options.each do |option|
        %li.grid__item
          - input_id = "option_#{option.id}".to_sym
          = f.input input_id, hint: option.description, label: option.id.humanize

  .form-actions
    = f.button :submit

app/views/scenes/edit.html.haml
%h1 Editing scene

= render 'form'

= link_to 'Show', @scene
\|
= link_to 'Back', scenes_path

app/views/scenes/index.html.haml
%h1 Listing scenes

%table{width: '100%'}
  %thead{style: 'visibility: collapse;'}
    %tr
      %th{width: 70} Preview
      %th Title
      -# TODO show user for admin
      -#%th User
      %th{width: 300} Progress
      - if user_is_admin?
        %th{width: 100} Actions
        -#%th
        -#%th

  %tbody
    - @scenes.each do |scene|
      = link_to scene do
        %tr
          %td
            - unless scene.result.blank?
              = image_tag scene.result.url(:thumb)
          %td= link_to scene.title, scene
          -#%td= scene.user.name
          %td
            - completed_percent = scene.amount_done * 100
            - extra_classes = completed_percent == 100 ? 'success' : ''
            .progress{class: extra_classes}
              %span.meter{style: "width: #{completed_percent}%"}
          - if user_is_admin?
            %td= link_to 'Destroy', scene, :method => :delete, :data => { :confirm => 'Are you sure?' }
            -#%td= link_to 'Show', scene
            -#%td= link_to 'Edit', edit_scene_path(scene)

%br

= link_to 'New Scene', new_scene_path

app/views/scenes/new.html.haml
%h1 New scene

= render 'form'

= link_to 'Back', scenes_path

app/views/scenes/renderer.html.haml
- content_for :title do
  = t 'scene.renderer_selection.title'

%h1=yield(:title)

%p= t 'scene.renderer_selection.text'

%ul.small-block-grid-3.medium-block-grid-6
  - @renderers.each do |renderer|
    %li.grid__item
      = link_to new_scene_path(renderer: renderer.name) do
        .row
          .small-4.columns
            .row
              = image_tag "icons/renderers/#{renderer.name}.png", class: %w(icon medium)
          .small-8.columns.text-right
            .row
              = renderer.name

app/views/scenes/show.html.haml
- content_for :title do
  = @scene.title

%h1=yield(:title)

%h2 Render setup

.row
  .small-12.columns
    %ul.small-block-grid-2.medium-block-grid-4
      - @scene.options.each do |key, value|
        %li.grid__item
          %div
            %label= key
            %p= value

%h2 Render tasks

.row
  .small-12.columns
    %ul.small-block-grid-2.medium-block-grid-4
      - @scene.jobs.each do |job|
        %li.text-center.grid__item
          - if job.result.blank?
            %div
              .row
                .small-12.columns
                  = job.name
              .row
                .small-12.columns
                  - state_class = "state-#{job.state}"
                  .icon{ class: state_class }
          - else
            = link_to job.result.url(:original), target: :blank do
              %div
                .row
                  .small-12.columns
                    = job.name
                .row
                  .small-12.columns
                    = image_tag(job.result.url(:medium))

= link_to 'Edit', edit_scene_path(@scene)
\|
= link_to 'Back', scenes_path