config/routes.rb
Rails.application.routes.draw do
  resources :scenes do
    get 'renderer', on: :new
    resources :jobs, shallow: true
  end
  resources :users
  resources :nodes, only: [:show, :index], constraints: { id: /[^\/]+/ }, format: false
  resources :renderers, only: [:show, :index, :update], constraints: { id: /[^\/]+/ }, format: false
  resources :options, only: [:show, :index, :update]
  root to: 'visitors#index'
  match '/auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/option.rb
# An adaptor option, not backed by app's DB
class Option < Fitrender::Option
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include Modelable
  extend Adaptorable

  def self.all
    option_hashes = get 'options'
    option_hashes.inject([]) do |arr, option_hash|
      arr << self.from_hash(option_hash)
    end
  end

  def self.find(option_id)
    self.from_hash(get "options/#{option_id}")
  end

  def update(*args)
    args.each do |arg|
      self.value = arg['value'] if arg.has_key? 'value'
    end
    self.save
  end

  def save
    Option.patch "options/#{id}", value: value
  end

  def to_key
    return *self.id
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_option, only: [:show, :edit, :update]

  # GET /scenes
  def index
    @options = Option.all
  end

  # GET /options/1
  def show
  end

  # GET /options/1/edit
  def edit
  end

  # PATCH/PUT /options/1
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to options_url, notice: 'Option was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_option
    @option = Option.find(params[:id])
  end

  def option_params
    params.require(:option).permit(:value)
  end
end

app/views/options/index.html.haml
- content_for :title do
  = t 'option.title'

%h1=yield(:title)

%h2 Global

%ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3
  - @options.each do |option|
    %li.grid__item
      %div
        = simple_form_for(option) do |f|
          .row
            .small-12.columns= f.error_notification
          .row
            .small-12.columns= f.input :value, hint: option.description, label: option.id.humanize
          .row
            .small-12.columns= f.button :submit

%h2 Renderer options

=link_to 'List renderers', renderers_path