config/routes.rb
Rails.application.routes.draw do
  resources :scenes do
    get 'renderer', on: :new
    resources :jobs, shallow: true
  end
  resources :users
  resources :nodes, only: [:show, :index], constraints: { id: /[^\/]+/ }, format: false
  resources :renderers, only: [:show, :index, :update], constraints: { id: /[^\/]+/ }, format: false
  resources :options, only: [:show, :index, :update]
  root to: 'visitors#index'
  match '/auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
.contain-to-grid
  %nav.top-bar{"data-topbar" => true}
    %ul.title-area
      %li.name
        = link_to root_path do
          = image_tag 'fitrender_logo.png', class: 'logo'
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          Menu
    .top-bar-section
      %ul
        = render 'layouts/navigation_links'
      %ul.right
        - if user_signed_in?
          %li
            = link_to 'New Scene', new_scene_path
          %li
            = link_to '' do
              =current_user.name
              =" (ID: #{current_user.id}, R: #{current_user.role})"
          %li= link_to 'Sign out', signout_path
        - else
          %li= link_to 'Sign in', signin_path
          - unless Rails.env.production?
            %li= link_to 'Sign in DEVELOPER', signin_path(developer: true)

app/views/layouts/_navigation_links.html.haml
=# add navigation links to this file
- if user_signed_in?
  %li= link_to 'Scenes', scenes_path
  - if user_is_admin?
    %li= link_to 'Nodes', nodes_path
    %li= link_to 'Backend Options', options_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? "FITRender | #{yield(:title)}" : 'FITRender'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Fitrender Frontend'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    %link{href:'http://fonts.googleapis.com/css?family=Lato:400,900,400italic,900italic&subset=latin,latin-ext', rel: 'stylesheet', type: 'text/css'}
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .row
        .small-12.columns
          .row
            = render 'layouts/messages'
            = yield